# Generated by Django 4.2.2 on 2023-06-26 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_alter_replyvotes_reply_alter_replyvotes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replyvotes',
            name='reply',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forum.reply'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='replyvotes',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
