# Generated by Django 4.2.2 on 2023-06-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_replyvotes_reply_alter_replyvotes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replyvotes',
            name='upvote',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='threadvotes',
            name='upvote',
            field=models.BooleanField(default=True),
        ),
    ]
